disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "sdnworks.com"
contentDir = 'content/en'

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "SDN Works - Alessandro Zanotti"
  email = "alessandro@zanotti.io"
  image = "img/Foto_profilo_centrata.png"
  imageQuality = 96
  # headline = "I'm only human"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:alessandro@zanotti.io" },
    { github = "https://github.com/azanotti" },
    { linkedin = "https://it.linkedin.com/in/alezanotti" }
  ]