# config/_default/menus.en.toml

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About me"
  pageRef = "aboutme"
  weight = 20

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20